spring:
  application:
    name: API-Gateway-TBNP
    

      
server: 
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: https://tbnp-eureka.herokuapp.com//eureka
  instance:
    prefer-ip-address: true
    
zuul:
  ignoredServices: '*'
  prefix: /tbnp-api
  routes:
    produto-service:
      path: /ms-produto/**
      serviceId: TESTE-BNP-MICROSERVICO_PRODUTO
    movimento-service:
      path: /ms-movimento/**
      serviceId: TESTE-BNP-CONSULTAMOVIMENTO
     
      
  host:
    socket-timeout-millis: 300000
    
